// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exam_entity;

#nullable disable

namespace exam_entity.Migrations
{
    [DbContext(typeof(BookShopDbContext))]
    partial class BookShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exam_entity.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 12,
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 12,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 11,
                            Name = "Virginia Woolf"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 11,
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 11,
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Name = "Ivan Franko"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Name = "Lesya Ukrainka"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Name = "Nikolai Gogol"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Name = "Taras Shevchenko"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            Name = "Franz Kafka"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            Name = "Thomas Mann"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 3,
                            Name = "Hermann Hesse"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 3,
                            Name = "Johann Wolfgang von Goethe"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 15,
                            Name = "Gabriel Garcia Marquez"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 19,
                            Name = "Mario Vargas Llosa"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 19,
                            Name = "Isabel Allende"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 20,
                            Name = "Haruki Murakami"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 20,
                            Name = "Yukio Mishima"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 12,
                            Name = "Jhumpa Lahiri"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 12,
                            Name = "Toni Morrison"
                        });
                });

            modelBuilder.Entity("exam_entity.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("BookInStoreId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("GenreId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            GenreId = 1,
                            Pages = 128,
                            PublicationYear = 1952,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            GenreId = 1,
                            Pages = 180,
                            PublicationYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            GenreId = 1,
                            Pages = 209,
                            PublicationYear = 1927,
                            Title = "To the Lighthouse"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            GenreId = 2,
                            Pages = 328,
                            PublicationYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            GenreId = 3,
                            Pages = 1178,
                            PublicationYear = 1954,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            GenreId = 4,
                            Pages = 392,
                            PublicationYear = 1882,
                            Title = "Zahar Berkut"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            GenreId = 4,
                            Pages = 96,
                            PublicationYear = 1911,
                            Title = "Forest Song"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            GenreId = 4,
                            Pages = 432,
                            PublicationYear = 1842,
                            Title = "Dead Souls"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            GenreId = 4,
                            Pages = 352,
                            PublicationYear = 1840,
                            Title = "Kobzar"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            GenreId = 5,
                            Pages = 224,
                            PublicationYear = 1925,
                            Title = "The Trial"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            GenreId = 5,
                            Pages = 720,
                            PublicationYear = 1924,
                            Title = "The Magic Mountain"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 12,
                            GenreId = 5,
                            Pages = 152,
                            PublicationYear = 1922,
                            Title = "Siddhartha"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 13,
                            GenreId = 6,
                            Pages = 356,
                            PublicationYear = 1808,
                            Title = "Faust"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 14,
                            GenreId = 1,
                            Pages = 288,
                            PublicationYear = 1932,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            GenreId = 2,
                            Pages = 544,
                            PublicationYear = 1866,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            GenreId = 3,
                            Pages = 352,
                            PublicationYear = 1813,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            GenreId = 4,
                            Pages = 1232,
                            PublicationYear = 1862,
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            GenreId = 2,
                            Pages = 824,
                            PublicationYear = 1880,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 19,
                            GenreId = 4,
                            Pages = 1440,
                            PublicationYear = 1869,
                            Title = "War and Peace"
                        });
                });

            modelBuilder.Entity("exam_entity.Entities.BookInStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BooksInStore");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Cost = 10.99,
                            Discount = 45,
                            Price = 19.989999999999998,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            Cost = 15.99,
                            Discount = 35,
                            Price = 24.989999999999998,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            Cost = 8.9900000000000002,
                            Discount = 40,
                            Price = 14.99,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            Cost = 5.9900000000000002,
                            Discount = 40,
                            Price = 9.9900000000000002,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            Cost = 18.989999999999998,
                            Discount = 35,
                            Price = 29.989999999999998,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            Cost = 7.9900000000000002,
                            Discount = 38,
                            Price = 12.99,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            Cost = 12.99,
                            Discount = 40,
                            Price = 21.989999999999998,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            Cost = 11.99,
                            Discount = 40,
                            Price = 19.989999999999998,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            Cost = 9.9900000000000002,
                            Discount = 41,
                            Price = 16.989999999999998,
                            Quantity = 22
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            Cost = 13.99,
                            Discount = 40,
                            Price = 23.989999999999998,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            Cost = 16.989999999999998,
                            Discount = 35,
                            Price = 27.989999999999998,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            Cost = 14.99,
                            Discount = 40,
                            Price = 24.989999999999998,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            Cost = 20.989999999999998,
                            Discount = 35,
                            Price = 32.990000000000002,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            Cost = 6.9900000000000002,
                            Discount = 37,
                            Price = 10.99,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            Cost = 17.989999999999998,
                            Discount = 35,
                            Price = 28.989999999999998,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 16,
                            BookId = 16,
                            Cost = 10.99,
                            Discount = 38,
                            Price = 17.989999999999998,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 17,
                            BookId = 17,
                            Cost = 7.9900000000000002,
                            Discount = 38,
                            Price = 12.99,
                            Quantity = 19
                        },
                        new
                        {
                            Id = 18,
                            BookId = 18,
                            Cost = 9.9900000000000002,
                            Discount = 41,
                            Price = 16.989999999999998,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 19,
                            BookId = 19,
                            Cost = 11.99,
                            Discount = 40,
                            Price = 19.989999999999998,
                            Quantity = 12
                        });
                });

            modelBuilder.Entity("exam_entity.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "France"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 11,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 12,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 18,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 19,
                            Name = "China"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Japan"
                        });
                });

            modelBuilder.Entity("exam_entity.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 18,
                            Name = "War"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("exam_entity.Entities.Author", b =>
                {
                    b.HasOne("exam_entity.Entities.Country", "Country")
                        .WithMany("Authors")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("exam_entity.Entities.Book", b =>
                {
                    b.HasOne("exam_entity.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exam_entity.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("exam_entity.Entities.BookInStore", b =>
                {
                    b.HasOne("exam_entity.Entities.Book", "Book")
                        .WithOne("BookInStore")
                        .HasForeignKey("exam_entity.Entities.BookInStore", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("exam_entity.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("exam_entity.Entities.Book", b =>
                {
                    b.Navigation("BookInStore")
                        .IsRequired();
                });

            modelBuilder.Entity("exam_entity.Entities.Country", b =>
                {
                    b.Navigation("Authors");
                });

            modelBuilder.Entity("exam_entity.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
